services:
  authentication-module:
    build: ./Authentication_Module
    ports:
      - "8000:8000"
    restart: always

  event-management-module:
    build: ./Event_Management_Module
    ports:
      - "8001:8001"
    restart: always

  booking-module:
    build: ./Booking_Module
    ports:
      - "3001:3001"
    restart: always

  venue-management-module:
    build: ./Venue_Management_Module
    ports:
      - "5193:5193"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - authentication-module
      - event-management-module
    restart: always